### ISSUE TITLE
Please Share Packer Code

### ISSUE THREAD

**Issue by maxywb** [canimus/hadoop273#1]
I'm assuming you're using Packer to build [the image you have on Atlas](https://atlas.hashicorp.com/canimus/boxes/hadoop273/). Could you move that code into this repo as well? IMO it's very relevant to showing how to setup the HDFS cluster.

**Comment by canimus** [comment]
Hi @maxywb the image in Hashicorp is an ubuntu/trusty64 image, with Java8 from Oracle installed. I guess if the idea was to start from really scratch, then that would be the starting point. For the packing mechanism I did use vagrant box mechanism.

``` shell
sudo apt-get clean
sudo dd if=/dev/zero of=/EMPTY bs=1M
sudo rm -f /EMPTY
cat /dev/null > ~/.bash_history && history -c && exit
vagrant package --output hadoop273.box
vagrant box add hadoop273 hadoop273.box
vagrant destroy
```

**Comment by canimus** [comment]
As per previous code. Considering this one closed.
