### ISSUE TITLE
Documentation :: Improvement

### ISSUE THREAD

**Issue by MrBeerBrewer** [canimus/hadoop273#2]
Greetings,

Can you please tell me the basic steps to use this box?
I have got to a point where it boots up. Now, I am clueless what to do?

I am able to access the box as using putty:
[https://i.imgsafe.org/382c639425.jpg](url)

I am quite new to Github, please excuse me if I did something wrong.

Regards,
Santosh

**Comment by canimus** [comment]
Hi, @MrBeerBrewer the setup is very simplistic. You can now play by logging into the Name Node or the Data Nodes, and run some of the typical commands in HDFS.
I added some comments in the README.md to use the playground.

**Comment by canimus** [comment]
Added new comments in the README.md file to give a head start in how to use the instances.

**Comment by MrBeerBrewer** [comment]
Greetings,
Thank you very much for responding. I will check the instructions.
Have a wonderful day ahead.
Regards,
Santosh
